# Build Stage
FROM node:22-alpine AS build

ARG REACT_APP_BACKEND_URL
ENV REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

WORKDIR /frontend

COPY package*.json /frontend
RUN npm install

COPY . /frontend
RUN REACT_APP_BACKEND_URL=$REACT_APP_BACKEND_URL npm run build
 
# Production Stage
FROM nginx:stable-alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /frontend/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
