# Generated by Django 5.1.7 on 2025-06-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Digital_Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '19. Digital sustainability keywords',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('1.A', '1.A Mobilisation of resources to end poverty'), ('4.7', '4.7 Education for sustainable development and global citizenship'), ('3.5', '3.5 Prevent and treat substance abuse'), ('3.3', '3.3 Fight communicable diseases'), ('2.5', '2.5 Maintain the genetic diversity in food production'), ('4.6', '4.6 Universal literacy and numeracy'), ('4.3', '4.3 Equal access to affordable technical, vocational and higher education'), ('3.6', '3.6 Reduce road injuries and deaths'), ('1.5', '1.5 Build resilience to environmental, economic and social disasters'), ('4.B', '4.B Expand higher education scholarships for developing countries'), ('5.5', '5.5 Ensure full participation in leadership and decision-making'), ('4.C', '4.C Increase the supply of qualified teachers in developing countries'), ('5.2', '5.2 End all violence against and exploitation of women and girls'), ('2.2', '2.2 End all forms of malnutrition'), ('1.1', '1.1 Eradicate extreme poverty'), ('1.3', '1.3 Implement social protection systems'), ('3.7', '3.7 Universal access to sexual and reproductive care, family planning and education'), ('4.5', '4.5 Eliminate all discrimination in education'), ('3.C', '3.C Increase health financing and support health workforce in developing countries'), ('2.B', '2.B Prevent agricultural trade restrictions, market distortions and export subsidies'), ('3.2', '3.2 End all preventable deaths under 5 years of age'), ('5.A', '5.A Equal rights to economic resources, property ownership and financial services'), ('4.2', '4.2 Equal access to quality pre-primary education'), ('3.A', '3.A Implement the WHO framework convention on tobacco control'), ('5.1', '5.1 End discrimination against women and girls'), ('5.B', '5.B Promote empowerment of women through technology'), ('2.C', '2.C Ensure stable food commodity markets and timely access to information'), ('4.1', '4.1 Free primary and secondary education'), ('5.4', '5.4 Value unpaid care and promote shared domestic responsibilities'), ('1.4', '1.4 Equal rights to ownership, basic services, technology and economic resources'), ('2.4', '2.4 Sustainable food production and resilient agricultural practices'), ('3.B', '3.B Support research, development and universal access to affordable vaccines and medicines'), ('3.D', '3.D Improve early warning systems for global health risks'), ('2.A', '2.A Invest in rural infrastructure, agricultural research, technology and gene banks'), ('5.6', '5.6 Universal access to reproductive health and rights'), ('4.A', '4.A Build and upgrade inclusive and safe schools'), ('1.2', '1.2 Reduce poverty by at least 50%'), ('1.B', '1.B Create Pro-poor and Gender-sensitive policy framewords'), ('5.C', '5.C Adopt and strengthen policies and enforceable legislation for gender equality'), ('5.7', '5.7 Universal access to sexual and reproductive care, family planning and education'), ('3.8', '3.8 Achieve universal health coverage'), ('2.1', '2.1 Universal access to safe and nutritious food'), ('3.1', '3.1 Reduce maternal mortality'), ('3.4', '3.4 Reduce mortality from non-communicable diseases and promote mental health'), ('4.4', '4.4 Increase the number of people with relevant skills for financial success'), ('2.3', '2.3 Double the productivity and incomes of small-scale food producers'), ('3.9', '3.9 Reduce illnesses and deaths from hazardous chemicals and pollution'), ('5.3', '5.3 Eliminate forced marriages and genital mutilation')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Adding Keywords',
            },
        ),
        migrations.CreateModel(
            name='keywords_related_to_all_SDGs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '18. keyword related to all SDGs',
            },
        ),
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': '20. Sources',
            },
        ),
        migrations.CreateModel(
            name='SDG10_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('10.1', '10.1 Reduce income inequalities'), ('10.2', '10.2 Promote universal social, economic and political inclusion'), ('10.3', '10.3 Ensure equal opportunities and end discrimination'), ('10.4', '10.4 Adopt fiscal and social policies that promotes equality'), ('10.5', '10.5 Improved regulation of global financial markets and institutions'), ('10.6', '10.6 Enhanced representation for developing countries in financial institutions'), ('10.A', '10.A Special and differential treatment for developing countries'), ('10.B', '10.B Encourage development assistance and investment in least developed countries'), ('10.C', '10.C Reduce transaction costs for migrant remittances')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '10. SDG 10 Reduced Inequalities',
            },
        ),
        migrations.CreateModel(
            name='SDG11_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('11.1', '11.1 Safe and affordable housing'), ('11.2', '11.2 Affordable and sustainable transport systems'), ('11.3', '11.3 Inclusive and sustainable urbanization'), ('11.4', "11.4 Protect the world's cultural and natural heritage"), ('11.5', '11.5 Reduce the adverse effects of natural disasters'), ('11.6', '11.6 Reduce the environmental impacts of cities'), ('11.7', '11.7 Provide access to safe and inclusive green and public spaces'), ('11.A', '11.A Strong national and regional development planning'), ('11.B', '11.B Implement policies for inclusion, resource efficiency and disaster risk reduction'), ('11.C', '11.C Support least developed countries in sustainable and resilient building')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '11. SDG 11 Sustainable Cities and Communities',
            },
        ),
        migrations.CreateModel(
            name='SDG12_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('12.1', '12.1 Implement the 10-year sustainable consumption and production framework'), ('12.2', '12.2 Sustainable management and use of natural resources'), ('12.3', '12.3 Halve global per capita food waste'), ('12.4', '12.4 Responsible management of chemicals and waste'), ('12.5', '12.5 Substantially reduce waste generation'), ('12.6', '12.6 Encourage companies to adopt sustainable practices and sustainability reporting'), ('12.7', '12.7 Promote sustainable public procurement practices'), ('12.8', '12.8 Promote universal understanding of sustainable lifestyles'), ('12.A', "12.A Support developing countries' scientific and technological capacity for sustainable consumption and production"), ('12.B', '12.B Develop and implement tools to monitor sustainable tourism'), ('12.C', '12.C Remove market distortions that encourage wasteful consumption')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '12. SDG 12 Responsible Consumption and Production',
            },
        ),
        migrations.CreateModel(
            name='SDG13_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('13.1', '13.1 Strengthen resilience and adaptive capacity to climate-related disasters'), ('13.2', '13.2 Integrate climate change measures into policy and planning'), ('13.3', '13.3 Build knowledge and capacity to meet climate change'), ('13.A', '13.A Implement the UN Framework Convention on Climate Change'), ('13.B', '13.B Promote mechanisms to raise capacity for planning and management')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '13. SDG 13 Climate Action',
            },
        ),
        migrations.CreateModel(
            name='SDG14_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('14.1', '14.1 Reduce marine pollution'), ('14.2', '14.2 Protect and restore ecosystems'), ('14.3', '14.3 Reduce ocean acidification'), ('14.4', '14.4 Sustainable fishing'), ('14.5', '14.5 Conserve coastal and marine areas'), ('14.6', '14.6 End subsidies contributing to overfishing'), ('14.7', '14.7 Increase the economic benefits from sustainable use of marine resource'), ('14.A', '14.A Increase scientific knowledge, research and technology for ocean health'), ('14.B', '14.B Support small scale fishers'), ('14.C', 'Implement and enforce international sea law')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '14. SDG 14 Life Below Water',
            },
        ),
        migrations.CreateModel(
            name='SDG15_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('15.1', '15.1 Conserve and restore terrestrial and freshwater ecosystems'), ('15.2', '15.2 End deforestation and restore degraded forests'), ('15.3', '15.3 End desertification and restore degraded land'), ('15.4', '15.4 Ensure conservation of mountain ecosystems'), ('15.5', '15.5 Protect biodiversity and natural habitats'), ('15.6', '15.6 Protect access to genetic resources and fair sharing of the benefits'), ('15.7', '15.7 Eliminate poaching and trafficking of protected species'), ('15.8', '15.8 Prevent invasive alien species on land and in water ecosystems'), ('15.9', '15.9 Integrate ecosystem and biodiversity in governmental planning'), ('15.A', '15.A Increase financial resources to conserve and sustainably use ecosystem and biodiversity'), ('15.B', '15.B Finance and incentivize sustainable forest management'), ('15.C', '15.C Combat global poaching and trafficking')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '15. SDG 15 Life on Land',
            },
        ),
        migrations.CreateModel(
            name='SDG16_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('16.1', '16.1 Reduce violence everywhere'), ('16.2', '16.2 Protect children from abuse, exploitation, trafficking and violence'), ('16.3', '16.3 Promote the rule of law and ensure equal access to justice'), ('16.4', '16.4 Combat organized crime and illicit financial and arms flows'), ('16.5', '16.5 Substantially reduce corruption and bribery'), ('16.6', '16.6 Develop effective, accountable and transparent institutions'), ('16.7', '16.7 Ensure responsive, inclusive and representative decision-making'), ('16.8', '16.8 Strengthen the participation in global governance'), ('16.9', '16.9 Provide universal legal identity'), ('16.10', '16.10 Ensure public access to information and protect fundamental freedoms'), ('16.A', '16.A Strengthen national institutions to prevent violence and combat crime and terrorism'), ('16.B', '16.B Promote and enforce non-discriminatory laws and policies')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '16. SDG 16 Justice, Peace and Strong Institutions',
            },
        ),
        migrations.CreateModel(
            name='SDG17_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('17.1', '17.1 Mobilize resources to improve domestic revenue collection'), ('17.2', '17.2 Implement all development assistance commitments'), ('17.3', '17.3 Mobilize financial resources for developing countries'), ('17.4', '17.4 Assist developing countries in attaining debt sustainability'), ('17.5', '17.5 Invest in least-developed countries'), ('17.6', '17.6 Knowledge sharing and cooperation for access to science, technology and innovation'), ('17.7', '17.7 Promote sustainable technologies to developing countries'), ('17.8', '17.8 Strengthen the participation in global governance'), ('17.9', '17.9 Enhanced SDG capacity in developing countries'), ('17.10', '17.10 Promote a universal trading system under the WTO'), ('17.11', '17.11 Increase the exports of developing countries'), ('17.12', '17.12 Remove trade barriers for least-developed countries'), ('17.13', '17.13 Enhance global macroeconomic stability'), ('17.14', '17.14 Enhance policy coherence for sustainable development'), ('17.15', '17.15 Respect national leadership to implement policies for the sustainable development goals'), ('17.16', '17.16 Enhance the global partnership for sustainable development'), ('17.17', '17.17 Encourage effective partnerships'), ('17.18', '17.18 Enhance availability of reliable data'), ('17.19', '17.19 Further develop measurements of progress')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '17. SDG 17 Partnership for the Goals',
            },
        ),
        migrations.CreateModel(
            name='SDG1_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('1.1', '1.1 Eradicate extreme poverty'), ('1.2', '1.2 Reduce poverty by at least 50%'), ('1.3', '1.3 Implement social protection systems'), ('1.4', '1.4 Equal rights to ownership, basic services, technology and economic resources'), ('1.5', '1.5 Build resilience to environmental, economic and social disasters'), ('1.A', '1.A Mobilisation of resources to end poverty'), ('1.B', '1.B Create Pro-poor and Gender-sensitive policy framewords')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '01. SDG 1 No Poverty',
            },
        ),
        migrations.CreateModel(
            name='SDG2_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('2.1', '2.1 Universal access to safe and nutritious food'), ('2.2', '2.2 End all forms of malnutrition'), ('2.3', '2.3 Double the productivity and incomes of small-scale food producers'), ('2.4', '2.4 Sustainable food production and resilient agricultural practices'), ('2.5', '2.5 Maintain the genetic diversity in food production'), ('2.A', '2.A Invest in rural infrastructure, agricultural research, technology and gene banks'), ('2.B', '2.B Prevent agricultural trade restrictions, market distortions and export subsidies'), ('2.C', '2.C Ensure stable food commodity markets and timely access to information')], default='', max_length=200)),
                ('note', models.CharField(default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': '02. SDG 2 Zero Hunger',
            },
        ),
        migrations.CreateModel(
            name='SDG3_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('3.1', '3.1 Reduce maternal mortality'), ('3.2', '3.2 End all preventable deaths under 5 years of age'), ('3.3', '3.3 Fight communicable diseases'), ('3.4', '3.4 Reduce mortality from non-communicable diseases and promote mental health'), ('3.5', '3.5 Prevent and treat substance abuse'), ('3.6', '3.6 Reduce road injuries and deaths'), ('3.7', '3.7 Universal access to sexual and reproductive care, family planning and education'), ('3.8', '3.8 Achieve universal health coverage'), ('3.9', '3.9 Reduce illnesses and deaths from hazardous chemicals and pollution'), ('3.A', '3.A Implement the WHO framework convention on tobacco control'), ('3.B', '3.B Support research, development and universal access to affordable vaccines and medicines'), ('3.C', '3.C Increase health financing and support health workforce in developing countries'), ('3.D', '3.D Improve early warning systems for global health risks')], default='', max_length=200)),
                ('note', models.CharField(default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': '03. SDG 3 Good Health and Well-being',
            },
        ),
        migrations.CreateModel(
            name='SDG4_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('4.1', '4.1 Free primary and secondary education'), ('4.2', '4.2 Equal access to quality pre-primary education'), ('4.3', '4.3 Equal access to affordable technical, vocational and higher education'), ('4.4', '4.4 Increase the number of people with relevant skills for financial success'), ('4.5', '4.5 Eliminate all discrimination in education'), ('4.6', '4.6 Universal literacy and numeracy'), ('4.7', '4.7 Education for sustainable development and global citizenship'), ('4.A', '4.A Build and upgrade inclusive and safe schools'), ('4.B', '4.B Expand higher education scholarships for developing countries'), ('4.C', '4.C Increase the supply of qualified teachers in developing countries')], default='', max_length=200)),
                ('note', models.CharField(default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': '04. SDG 4 Quality Education',
            },
        ),
        migrations.CreateModel(
            name='SDG5_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('5.1', '5.1 End discrimination against women and girls'), ('5.2', '5.2 End all violence against and exploitation of women and girls'), ('5.3', '5.3 Eliminate forced marriages and genital mutilation'), ('5.4', '5.4 Value unpaid care and promote shared domestic responsibilities'), ('5.5', '5.5 Ensure full participation in leadership and decision-making'), ('5.6', '5.6 Universal access to reproductive health and rights'), ('5.7', '5.7 Universal access to sexual and reproductive care, family planning and education'), ('5.A', '5.A Equal rights to economic resources, property ownership and financial services'), ('5.B', '5.B Promote empowerment of women through technology'), ('5.C', '5.C Adopt and strengthen policies and enforceable legislation for gender equality')], default='', max_length=200)),
                ('note', models.CharField(default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': '05. SDG 5 Gender Equality',
            },
        ),
        migrations.CreateModel(
            name='SDG6_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
                ('target', models.CharField(choices=[('6.1', '6.1 Safe and affordable drinking water'), ('6.2', '6.2 End open defecation and provide access to sanitation and hygiene'), ('6.3', '6.3 Improve water quality, wastewater treatment and safe reuse'), ('6.4', '6.4 Increase water use efficiency and ensure freshwater supplies'), ('6.5', '6.5 Implement integrated water resources management'), ('6.6', '6.6 Protect and restore water-related ecosystems'), ('6.A', '6.A Expand water and sanitation support to developing countries'), ('6.B', '6.B Support local engagement in water and sanitation management')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': '06. SDG 6 Clean Water and Sanitation',
            },
        ),
        migrations.CreateModel(
            name='SDG7_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('7.1', '7.1 Universal access to modern energy'), ('7.2', '7.2 Increase global percentage of renewable energy'), ('7.3', '7.3 Double the improvement in energy efficiency'), ('7.A', '7.A Promote access, technology and investments in clean energy'), ('7.B', '7.B Expand and upgrade energy services for developing countries')], default='', max_length=200)),
                ('note', models.CharField(default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
            ],
            options={
                'verbose_name_plural': '07. SDG 7 Affordable and Clean Energy',
            },
        ),
        migrations.CreateModel(
            name='SDG8_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('8.1', '8.1 Sustainable economic growth'), ('8.2', '8.2 Diversify, innovate and upgrade for economic productivity'), ('8.3', '8.3 Promote policies to support job creation and growing enterprises'), ('8.4', '8.4 Improve resource efficiency in consumption and production'), ('8.5', '8.5 Full employment and decent work with equal pay'), ('8.6', '8.6 Promote youth employment, education and training'), ('8.7', '8.7 End modern slavery, trafficking, and child labour'), ('8.8', '8.8 Protect labour rights and promote safe working environments'), ('8.9', '8.9 Promote beneficial and sustainable tourism'), ('8.10', '8.10 Universal access to banking, insurance and financial services'), ('8.a', '8.a Increase aid for trade support'), ('8.b', '8.b Develop a global youth employment strategy')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '08. SDG 8 Decent Work and Economic Growth',
            },
        ),
        migrations.CreateModel(
            name='SDG9_Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=200)),
                ('sdggoal', models.CharField(choices=[('1', 'SDG1 No Poverty'), ('2', 'SDG 2 Zero Hunger'), ('3', 'SDG 3 Good Health and Well-being'), ('4', 'SDG 4 Quality Education'), ('5', 'SDG 5 Gender Equality'), ('6', 'SDG 6 Clean Water and Sanitation'), ('7', 'SDG 7 Affordable and Clean Energy'), ('8', 'SDG 8 Decent Work and Economic Growth'), ('9', 'SDG 9 Industry, Innovation and Infrastructure'), ('10', 'SDG 10 Reduced Inequalities'), ('11', 'SDG 11 Sustainable Cities and Communities'), ('12', 'SDG 12 Responsible Consumption and Production'), ('13', 'SDG 13 Climate Action'), ('14', 'SDG 14 Life Below Water'), ('15', 'SDG 15 Life on Land'), ('16', 'SDG 16 Justice, Peace and Strong Institutions'), ('17', 'SDG 17 Partnership for the Goals')], default='', max_length=300)),
                ('target', models.CharField(choices=[('9.1', '9.1 Develop sustainable, resilient and inclusive infrastructures'), ('9.2', '9.2 Promote inclusive and sustainable industrialization'), ('9.3', '9.3 Increase access to financial services and markets'), ('9.4', '9.4 Upgrade all industries and infrastructures for sustainability'), ('9.5', '9.5 Enhance research and upgrade industrial technologies'), ('9.A', '9.A Facilitate sustainable infrastructure development for developing countries'), ('9.B', '9.B Support domestic technology development and industrial diversification'), ('9.C', '9.C Universal access to information and communications technology')], default='', max_length=200)),
                ('reference1', models.CharField(default='', max_length=300)),
                ('reference2', models.CharField(default='', max_length=300)),
                ('note', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name_plural': '09. SDG 9 Industry, Innovation and Infrastructure',
            },
        ),
    ]
