# Generated by Django 5.1.7 on 2025-06-15 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sdg_actions', '0001_initial'),
        ('sdg_education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionName', models.TextField()),
                ('related_sdgs', models.TextField(blank=True, null=True)),
                ('related_industries', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdg_actions.actiondb')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['actionId', 'userId'], name='admin_porta_actionI_7192e6_idx'), models.Index(fields=['timestamp'], name='admin_porta_timesta_66d20e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EducationInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationName', models.TextField()),
                ('related_sdgs', models.TextField(blank=True, null=True)),
                ('related_disciplines', models.TextField(blank=True, null=True)),
                ('related_industries', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('educationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdg_education.educationdb')),
                ('userId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['educationId', 'userId'], name='admin_porta_educati_1f871b_idx'), models.Index(fields=['timestamp'], name='admin_porta_timesta_6d688e_idx')],
            },
        ),
    ]
