# Generated by Django 5.1.7 on 2025-06-15 08:05

import django.core.validators
import multiselectfield.db.fields
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionDb',
            fields=[
                ('actions', models.CharField(blank=True, db_column='Actions', error_messages={'unique': 'The Action item you entered is not unique.'}, help_text='Warning: please check if there are similar items in the database.', max_length=255, null=True, verbose_name='Action Title')),
                ('action_detail', models.TextField(blank=True, db_column='Action detail', max_length=2048, null=True, verbose_name='Action Detail')),
                ('award', models.IntegerField(blank=True, choices=[(0, 'Individual'), (1, 'Organization'), (2, 'Both')], db_column='Award', null=True, verbose_name='Award')),
                ('award_description', models.TextField(blank=True, db_column='Award Descriptions', max_length=2048, null=True, verbose_name='Award Description')),
                ('sdgs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, 'ALL')], db_column=' SDGs', default='', max_length=64, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Related_SDGs')),
                ('level', models.IntegerField(blank=True, choices=[(1, 'Level 1 - on Couch, Individual action'), (2, 'Level 2 - at Home, Individual action'), (3, 'Level 3 - in Community, Individual action'), (4, 'Level 4 - at School and Workm Individual action'), (5, 'Level 5 - Organization action'), (6, 'Level 6 - Government action')], db_column='Level', null=True)),
                ('individual_organization', models.IntegerField(blank=True, choices=[(0, 'Individual'), (1, 'Organization'), (2, 'Both')], db_column='Individual/Organization', null=True, verbose_name='individual or organization')),
                ('location', models.TextField(blank=True, db_column='Location (specific actions/org onlyonly)', max_length=200, null=True, verbose_name='location')),
                ('digital_actions', models.IntegerField(blank=True, choices=[(0, 'YES'), (1, 'NO')], db_column='Digital actions', null=True)),
                ('related_industry', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Agriculture forestry and fishing', 'Agriculture forestry and fishing'), ('Mining', 'Mining'), ('Manufacturing', 'Manufacturing'), ('Electricity gas water and waste services', 'Electricity gas water and waste services'), ('Construction', 'Construction'), ('Wholesale and retail trade', 'Wholesale and retail trade'), ('Accommodation and food services', 'Accommodation and food services'), ('Transport postal and warehousing', 'Transport postal and warehousing'), ('Information media and telecommunications', 'Information media and telecommunications'), ('Financial and insurance services', 'Financial and insurance services'), ('Rental hiring and real estate services', 'Rental hiring and real estate services'), ('Professional services', 'Professional services'), ('Public administration and safety', 'Public administration and safety'), ('Education and training', 'Education and training'), ('Health care and social assistance', 'Health care and social assistance'), ('Arts and recreation services', 'Arts and recreation services')], db_column='Related Industry', max_length=200, null=True, verbose_name='Industry: (Tick up to 3 most relevant categories)')),
                ('sources', models.TextField(blank=True, db_column='Source descriptions', help_text='Description of the source, DO NOT PUT hyperlink.', null=True, verbose_name='Sources:')),
                ('links', models.TextField(blank=True, db_column='Source Links', help_text='Hyperlink only', null=True, verbose_name='Links:')),
                ('additional_notes', models.TextField(blank=True, db_column='Additional Notes', null=True)),
                ('column15', models.CharField(blank=True, db_column='Column15', max_length=50, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Action item',
                'verbose_name_plural': 'Action Database',
                'db_table': 'action_db',
                'managed': True,
            },
        ),
    ]
