# Generated by Django 5.1.7 on 2025-06-15 08:05

import django.core.validators
import multiselectfield.db.fields
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EducationDb',
            fields=[
                ('title', models.TextField(blank=True, db_column='Title', null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('aims', models.TextField(blank=True, db_column='Aims', null=True)),
                ('sdgs_related', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, 'ALL')], db_column='SDGs related', default='', max_length=100, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Related_SDGs')),
                ('learning_outcome', models.TextField(blank=True, db_column='Learning outcome( Expecting outcome)', null=True)),
                ('type_label', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Undergraduate course', 'Undergraduate course'), ('Postgraduate course', 'Postgraduate course'), ('Initiative', 'Initiative'), ('Event', 'Event'), ('Seminar', 'Seminar'), ('Undergraduate program', 'Undergraduate program'), ('Postgraduate program', 'Postgraduate program'), ('Practicum online course', 'Practicum online course'), ('MOOC', 'MOOC'), ('Case study', 'Case study'), ('Report', 'Report'), ('Blog', 'Blog'), ('Edu Tool', 'Edu Tool'), ('Simulation', 'Simulation'), ('Game', 'Game'), ('VR video', 'VR video'), ('Film', 'Film'), ('Contest', 'Contest')], db_column='Type label', max_length=100, null=True, verbose_name='Type: (Tick up to 3 most relevant categories)')),
                ('location', models.TextField(blank=True, choices=[('Australia', 'Australia'), ('Austria', 'Austria'), ('Brazil', 'Brazil'), ('Canada', 'Canada'), ('China Mainland', 'China Mainland'), ('European Union', 'European Union'), ('India', 'India'), ('Ireland', 'Ireland'), ('Italy', 'Italy'), ('Malaysia', 'Malaysia'), ('Mexico', 'Mexico'), ('New Zealand', 'New Zealand'), ('Russia', 'Russia'), ('Spain', 'Spain'), ('Sweden', 'Sweden'), ('Switzerland', 'Switzerland'), ('Taiwan ROC', 'Taiwan ROC'), ('United Kingdom', 'United Kingdom'), ('United States', 'United States'), ('Global', 'Global')], db_column='Location', null=True)),
                ('organization', models.TextField(blank=True, db_column='Organization', null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=50, null=True)),
                ('related_to_which_discipline', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Architecture and Building', 'Architecture and Building (Architecture, City Planning, Industrial Design, Landscape Architecture)'), ('Business and Management', 'Business and Management (Actuarial Studies, Business, Commerce, Finance, Property and Development)'), ('Creative Arts', 'Creative Arts (Art, Music, Design, Media)'), ('Education', 'Education'), ('Engineering and Related Technologies', 'Engineering and Related Technologies (Aerospace, Aviation, Civil, Electricity, Materials, Mechanics, Biomedical Engineering, Food, Mining)'), ('Environmental and Related Studies', 'Environmental and Related Studies (Environmental Management)'), ('Health', 'Health (Medicine, Nutrition, Psychology, Mental health, Ophthalmology, Public health)'), ('Humanities and Law', 'Humanities and Law (Art-culture, Criminology, Economics, Humanities, Law, Language Studies, aborigines, Social Sciences, Politics, Sociology, Philosophy, Tax)'), ('Information Technology', 'Information Technology '), ('Natural and Physical Sciences', 'Natural and Physical Sciences (Mathematics, Physics, Biology, Chemistry, Life sciences, Sciences)'), ('All', 'All')], db_column='Related to which discipline', max_length=1500, null=True, verbose_name='Related to which discipline: (Tick up to 3 most relevant categories)')),
                ('useful_for_which_industries', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Agriculture forestry and fishing', 'Agriculture forestry and fishing'), ('Mining', 'Mining'), ('Manufacturing', 'Manufacturing'), ('Electricity gas water and waste services', 'Electricity gas water and waste services'), ('Construction', 'Construction'), ('Wholesale and retail trade', 'Wholesale and retail trade'), ('Accommodation and food services', 'Accommodation and food services'), ('Transport postal and warehousing', 'Transport postal and warehousing'), ('Information media and telecommunications', 'Information media and telecommunications'), ('Financial and insurance services', 'Financial and insurance services'), ('Rental hiring and real estate services', 'Rental hiring and real estate services'), ('Professional services', 'Professional services'), ('Public administration and safety', 'Public administration and safety'), ('Education and training', 'Education and training'), ('Health care and social assistance', 'Health care and social assistance'), ('Arts and recreation services', 'Arts and recreation services')], db_column='Useful for which industries', max_length=1500, null=True, verbose_name='Useful for which industries: (Tick up to 3 most relevant categories)')),
                ('sources', models.TextField(blank=True, db_column='Source', null=True)),
                ('links', models.TextField(blank=True, db_column='Link', null=True)),
                ('descriptions', models.TextField(blank=True, db_column='descriptions', null=True)),
                ('column14', models.IntegerField(blank=True, db_column='Column14', null=True)),
                ('column15', models.CharField(blank=True, db_column='Column15', max_length=50, null=True)),
                ('column16', models.CharField(blank=True, db_column='Column16', max_length=50, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Education item',
                'verbose_name_plural': 'Education Database',
                'db_table': 'education_db',
                'managed': True,
            },
        ),
    ]
